apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "longnameforfancyproject.fullname" . }}
  labels:
    app: {{ include "longnameforfancyproject.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "longnameforfancyproject.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "longnameforfancyproject.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.db.hostname | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
          resources:
            {{- toYaml .Values.resources | nindent 12 }}